blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/vessy/ios-git/security/advisories/new
    about: Please report vulnerabilities privately.
